# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaed07fee14b0612da1cb1395312e63b9f26717488f1f99fcb676fd45ff4f76d0f5762329d1d52645e20b1622b935707308d6dfdda2a38f42849cd8ee82ab031

test:
  secret_key_base: 46cb874185f7e31704a8ddc03c8d4475e8b1d7cca6b635ed8fff639edd241188efa27094c088b1c012f82668df9e32beb43f9b36b8e7f4095fdbbeea2c279dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
